### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by NSQY** [dnjulek/vapoursynth-julek-plugin#1]
Arch Linux
GCC 12.2.0
R61

Needs ``-fPIC`` to compile, but then;

```vapoursynth.Error: Failed to load libjulek.so. libjulek.so: undefined symbol: _ZTVN3jxl22CustomTransferFunctionE```

**Comment by dnjulek** [comment]
Please try with the new CMakeLists and the new build instructions.

**Comment by NSQY** [comment]
Cmake finds ``/usr/lib/libjxl.so`` before ``thirdparty/libjxl``. Bypassed by removing ``/usr/lib/libjxl.so`` from my system before compiling.

This should be fixed, since if you ever plan on linking to custom builds of more popular libraries this could become messy.
